Name:           ros-hydro-head-pose-estimation
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS head_pose_estimation package

Group:          Development/Libraries
License:        Microsoft Shared Source
URL:            http://ros.org/wiki/head_pose_estimation
Source0:        %{name}-%{version}.tar.gz

Requires:       numpy
Requires:       ros-hydro-angles
Requires:       ros-hydro-cv-bridge
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-face-detector
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-transport
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-pcl-ros
Requires:       ros-hydro-people-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-tf
BuildRequires:  numpy
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cv-bridge
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-face-detector
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-transport
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-orocos-kdl
BuildRequires:  ros-hydro-pcl-ros
BuildRequires:  ros-hydro-people-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-tf

%description
ROS wrapper around Fanelli et al.'s Real Time Head Pose Estimation from Consumer
Depth Cameras. 33rd Annual Symposium of the German Association for Pattern
Recognition (DAGM'11), 2011.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Nov 11 2014 Dan Lazewatsky <dan@lazewatsky.com> - 1.0.3-0
- Autogenerated by Bloom

* Wed Oct 08 2014 Dan Lazewatsky <dan@lazewatsky.com> - 1.0.2-0
- Autogenerated by Bloom

* Tue Oct 07 2014 Dan Lazewatsky <dan@lazewatsky.com> - 1.0.1-0
- Autogenerated by Bloom

